env:
  es6: true
  node: true

extends:
  - eslint:recommended
  - nodejs-recommended

rules:
  import/no-commonjs: off

  lodash/prefer-lodash-method: off

  comma-dangle: [error, never]
  eol-last: error
  handle-callback-err: error
  indent: [error, 2]
  linebreak-style: [error, unix]
  no-magic-numbers: off
  quotes: [error, single]
  semi: [error, always]
